#!/bin/bash
#
#Copyright 2012 Hexagon <development@xbian.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>

_NAME="Updates"
_DESC="Check for system updates"

_DOWNLOAD_PL="Downloading package list ..."
_PL_ERROR="Package list could not be downloaded, try again later ..."
_CHECKING_FOR_UD="Checking for updates ..."
_UP_TO_DATE="Your system is up to date"
_ERROR_CHECK_UPDATE="An error occurred while checking for updates"
_AN_UPDATE="An update"
_IS_AVAILABLE="is available, do you wan't to update now?"
_INSTALLING_UPDATE="Installing update, please wait ..."
_UPDATED_TO="System updated to version"
