#!/bin/bash
#
#Copyright 2012 Hexagon <development@xbian.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>

_NAME="Updates"
_DESC="Check for system updates"

_DOWNLOADPL="Downloading package list ..."
_PLERROR="Package list could not be downloaded, try again later ..."
_CHECKINGFORUD="Checking for updates ..."
_UPTODATE="Your system is up to date"
_ERRORCHECKUPDATE="An error occurred while checking for updates"
_ANUPDATE="An update"
_ISAVAILABLE="is available, do you wan't to update now?"
_INSTALLINGUPDATE="Installing update, please wait ..."
_UPDATEDTO="System updated to version"
_ERRORUPDATE="An error occurred while installing the update"
