#!/bin/bash
#
#Copyright 2012 Hexagon <development@xbian.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>

_NAME="Updates"
_DESC="Controleer op systeem updates"

_DOWNLOADPL="Paketten lijst aan het downloaden..."
_PLERROR="Paketten lijst kon niet gedownload worden, probeer het later opnieuw..."
_CHECKINGFORUD="Aan het controleren op updates..."
_UPTODATE="Uw systeem is up-to-date"
_ERRORCHECKUPDATE="Er is een fout opgetreden tijdens het controleren op updates"
_ANUPDATE="Een update"
_ISAVAILABLE="is beschikbaar, wilt u nu bijwerken?"
_INSTALLINGUPDATE="Update aan het installeren, een ogenblik geduld aub..."
_UPDATEDTO="Systeem bijgewerkt naar versie"
_ERRORUPDATE="Er is een fout opgetreden tijdens het installeren van de update"
