#!/bin/bash
#
#Copyright 2012 CurlyMo <development@xbian.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>

#|------------------------------------|
#|          Global variables          |
#|------------------------------------|

# The arguments this module accepts
ARGUMENTS=(select insert delete update);

#|------------------------------------|
#|          Include files             |
#|------------------------------------|

source $BASEPATH/scripts/licensempg2/functions
source $BASEPATH/scripts/licensempg2/dialogs

#|------------------------------------|
#|           Main program             |
#|------------------------------------|

# Executes the GUI version of this module
function showGUIFn() {
	getCurrentLicenseMPG2Fn LICENSE
	CURRENTLICENSE=$LICENSE;
	showLicenseMPG2InputDlg $CURRENTLICENSE;
	if [ ! -z $RETURN ] && [ ! -z $CURRENTLICENSE ]; then
		updateLicenseMPG2Fn $RETURN $CURRENTLICENSE
		if [ $? -eq 1 ]; then
			showLicenseMPG2UpdatedDlg;
			ASKFORREBOOT=1;
		else
			showErrorDlg;
		fi
	elif [ ! -z $RETURN ] && [ -z $CURRENTLICENSE ]; then
		insertLicenseMPG2Fn $RETURN;
		if [ $? -eq 1 ]; then
			showLicenseMPG2InsertedDlg;
			ASKFORREBOOT=1;
		else
			showErrorDlg;
		fi
	elif [ -z $RETURN ] && [ -z $CURRENTLICENSE ]; then
		return 1;
	else
		deleteLicenseMPG2Fn $CURRENTLICENSE;
		if [ $? -eq 1 ]; then
			showLicenseMPG2DeletedDlg;
			ASKFORREBOOT=1;
		else
			showErrorDlg;
		fi
	fi
}

# Executes the command line version of this module
#  $1 Argument [Integer]
#  $2 Hostname [String]
# Returns
#  *Get [String]
#  - Hostname
#  *Set [Integer]
#  - 1: Success
#  - 0: Failed
function showCMDFn() {
	case $1 in
		"select")
			getCurrentLicenseMPG2Fn LICENSE;
			echo $LICENSE;
		;;
		"update")
			shift;
			if [ $# -eq 1 ]; then
				getCurrentLicenseMPG2Fn LICENSE
				updateLicenseMPG2Fn $1 $LICENSE;
				echo $?;
			else
				echo 0;
			fi
		;;
		"insert")
			shift;
			if [ $# -eq 1 ]; then
				insertLicenseMPG2Fn $1;
				echo $?;
			else
				echo 0;
			fi
		;;		
		"delete")
			getCurrentLicenseMPG2Fn LICENSE
			deleteLicenseMPG2Fn $LICENSE;
			echo $?;
		;;
	esac
}