#!/bin/bash
#
#Copyright 2012 CurlyMo <development@xbian.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>

#|------------------------------------|
#|          Global variables          |
#|------------------------------------|

# The arguments this module accepts
ARGUMENTS=(get set);

#|------------------------------------|
#|          Include files             |
#|------------------------------------|

source $BASEPATH/scripts/hostname/functions
source $BASEPATH/scripts/hostname/dialogs

#|------------------------------------|
#|           Main program             |
#|------------------------------------|

# Executes the GUI version of this module
function showGUIFn() {
	getCurrentHostnameFn HOSTNAME
	CURRENTHOSTNAME=$HOSTNAME;
	showHostnameInputDlg $CURRENTHOSTNAME;
	if [ ! -z $RETURN ]; then
		setHostnameFn $RETURN $CURRENTHOSTNAME
		if [ $? -eq 1 ]; then
			showHostnameSuccesDlg;
			ASKFORREBOOT=1;
		else
			showErrorDlg;
		fi
	fi
}

# Executes the command line version of this module
#  $1 Argument [Integer]
#  $2 Hostname [String]
# Returns
#  *Get [String]
#  - Hostname
#  *Set [Integer]
#  - 1: Success
#  - 0: Failed
function showCMDFn() {
	case $1 in
		"get")
			getCurrentHostnameFn HOSTNAME;
			echo $HOSTNAME;
		;;
		"set")
			shift;
			if [ $# -eq 1 ]; then
				getCurrentHostnameFn HOSTNAME
				setHostnameFn $1 $HOSTNAME;
				echo $?;
			else
				echo 0;
			fi
		;;
	esac
}