#!/bin/bash
#
#Copyright 2012 CurlyMo <development@xbian.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>

_NAME="XBMC"
_DESC="Cambiar ajustes de XBMC"
_XBMCWEBSERVERSUCCESS="Servidor web de XBMC añadido con éxito"
_XBMCWEBSERVERFAILED="Fallo, al iniciar el servidor web de XBMC"
_XBMCGUIRESSUCCESS="Resolución de la interfaz de XBMC cambiada con éxito"
_XBMCGUIRESFAILED="Fallo, al cambiar la resolución de la interfaz de XBMC"
_XBMCGUIRES="Resolución de la interfaz"
_XBMCWEBSERVER="Servidor web"
_XBMCACTIONS="Acciones"
_XBMCWEBSERVERENABLEDISABLE="¿Quieres activar o desactivar el servidor web?"