#!/bin/bash
#
#Copyright 2012 CurlyMo <development@xbian.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License,or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful,but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not,see <http://www.gnu.org/licenses/>

# Shows the overclocking warning
function showOCWarningDlg() {
	wrapTxtFn "$_OCWARNING"
	centerTxtFn "$WRAPPEDTXT"
	showMsgDlg "$WRAPPEDTXT" $HEIGHT
}

# Shows the overclocking settings radio dialog
#  $1 [Array] The rows of the radio dialog
function showOCSettingsDlg() {
	OCMENU=$1;
	createTableFn "radio"\
	"   #,\Zb$_OCNAME,\ZbARM,\ZbCORE,\ZbSDRAM,\ZbOvervolt"\
	"${OCMENU[@]}";
	centerTxtFn "$HEADER" $(($DEFAULTWIDTH+15))
	showRadioDlg "$CENTEREDTXT" "$ROWS" ${#OCMENU[@]} 16	
}

# Shows the overclocking settings not changed dialog
function showNoOCChangeDlg() {
	wrapTxtFn "$_OCNOTCHANGED"
	centerTxtFn "$WRAPPEDTXT"
	valignTxtFn "$CENTEREDTXT"
	showMsgDlg "$ALIGNEDTXT" $HEIGHT
}

# Shows the overclocking settings updated dialog
function showUpdatedOCDlg() {
	wrapTxtFn "$_OCCHANGED"
	centerTxtFn "$WRAPPEDTXT"
	valignTxtFn "$CENTEREDTXT"
	showMsgDlg "$ALIGNEDTXT" $HEIGHT
}

# Shows the custom overclocking settings dialog
#  $1 [Array] Space seperated values (ARM CORE SDRAM VOLTAGE) 
function showCustomOCDlg() {
	IFS=" ";
	SETTINGS=($1)
	IFS=$ORIGINALIFS;
	
	VALUES=$(dialog \
			--ok-label "$_CHANGE" \
			--cancel-label "$_RETURN" \
			--backtitle "$BACKTITLE" \
			--title "$TITLE" \
			--mixedform "" \
			10 $DEFAULTWIDTH 4 \
			"ARM Freq:" 1 3 "${SETTINGS[0]}" 1 16 5 4 0\
			"ARM Freq:" 1 3 "Mhz" 1 22 5 4 2\
			"Core Freq:"  2 3 "${SETTINGS[1]}" 2 16 4 3 0\
			"Core Freq:"  2 3 "Mhz" 2 21 4 3 2\
			"SDRAM Freq:"  3 3 "${SETTINGS[2]}" 3 16 4 3 0\
			"SDRAM Freq:"  3 3 "Mhz" 3 21 4 3 2\
			"Overvolt:"  4 3 "${SETTINGS[3]}" 4 16 2 1 0 \
			3>&1 1>&2 2>&3);
}

#Shows the empty fields dialog
function showOCEmptyFieldsDlg() {
	wrapTxtFn "$_OCEMPTYFIELDS"
	centerTxtFn "$WRAPPEDTXT"
	valignTxtFn "$CENTEREDTXT"
	showMsgDlg "$ALIGNEDTXT" $HEIGHT $DEFAULTWIDTH $_RETRY
	return $?;
} 