#!/bin/bash
#
#Copyright 2012 CurlyMo <development@xbian.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>

#|------------------------------------|
#|          Global variables          |
#|------------------------------------|

# The arguments this module accepts
ARGUMENTS=(select update);

#|------------------------------------|
#|          Include files             |
#|------------------------------------|

source $BASEPATH/modules/overclocking/functions
source $BASEPATH/modules/overclocking/dialogs

#|------------------------------------|
#|           Main program             |
#|------------------------------------|

# Executes the GUI version of this module
function showGUIFn() {
	#showOCWarningDlg;
	showOCSettingsDlg;
}

# Executes the command line version of this module
#  $1 Argument [String]
#  $2 Hostname [String]
# Returns
#  *Select [String]
#  - Hostname
#  *Update [Integer]
#  - 1: Success
#  - 0: Failed
function showCMDFn() {
	echo;
}