#!/bin/bash
#
#Copyright 2012 CurlyMo <development@xbian.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>

#|------------------------------------|
#|          Global variables          |
#|------------------------------------|

# The arguments this module accepts
ARGUMENTS=(select update);

#|------------------------------------|
#|          Include files             |
#|------------------------------------|

source $BASEPATH/modules/overclocking/functions
source $BASEPATH/modules/overclocking/dialogs
source $BASEPATH/functions/config

#|------------------------------------|
#|           Main program             |
#|------------------------------------|

# Executes the GUI version of this module
function showGUIFn() {
	#showOCWarningDlg;
	getCurrentOCSettingsFn;	
	STATUS=(off off off off off off off);

	case "${OCOLDSETTINGS[@]}" in
		"700 250 400 0")
			STATUS[0]="on";
		;;
		"800 300 400 0")
			STATUS[1]="on";
		;;
		"840 375 400 0")
			STATUS[2]="on";
		;;
		"900 333 450 0")
			STATUS[3]="on";
		;;
		"950 450 450 2")
			STATUS[4]="on";
		;;
		"1000 500 500 6")
			STATUS[5]="on";
		;;
		*)
			STATUS[6]="on";
		;;
	esac;

	showOCSettingsDlg $STATUS;
	if [ $? -eq 0 ]; then
		if [ ${STATUS[$(($RETURN-1))]} == "on" ]; then
			showNoOCChangeDlg;
		elif [ $RETURN -eq 7 ]; then
			#updateOCSettingsFn $RETURN;
			echo;
		else
			updateOCSettingsFn $RETURN;
			if [ $? -eq 1 ]; then
				showUpdatedOCDlg;
				ASKFORREBOOT=1;
			fi
		fi
	fi
}

# Executes the command line version of this module
#  $1 Argument [String]
#  $2 Hostname [String]
# Returns
#  *Select [String]
#  - Hostname
#  *Update [Integer]
#  - 1: Success
#  - 0: Failed
function showCMDFn() {
	echo;
}