#!/bin/bash
#
#Copyright 2012 CurlyMo <development@xbian.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>

_NAME="Overclocking"
_DESC="Configurar overclocking"
_OCWARNING="Overclocking extremo pode reduzir a vida útil do teu Raspberry Pi. XBian testou differentes definições de overclocking e criou uma combinação de definições preferencial. Overclock Turbo pode causar corrupção do sistema de ficheiros. O risco é seu!"
_OCNOTCHANGED="Estas definições de overclock já estavam selecionadas"
_OCCHANGED="As definições de overclock foram alteradas com sucesso"
_OCNAME="Nome"
_OCCUSTOM="~"
_OCEMPTYFIELDS="Não preencheste todos os campos"