#!/bin/bash
#
#Copyright 2012 CurlyMo <development@xbian.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>

function showPackageListDownloadDlg() {
        wrapTxtFn "$_DOWNLOADPL"
        centerTxtFn "$WRAPPEDTXT"
        showInfoDlg "$CENTEREDTXT"
}

function showPackageListErrorDlg() {
	wrapTxtFn "$_PLERROR"
	centerTxtFn "$WRAPPEDTXT"
	showMsgDlg "$CENTEREDTXT"
}

function showCheckingForUpdatesDlg() {
        wrapTxtFn "$_CHECKINGFORUD"
        centerTxtFn "$WRAPPEDTXT"
        showInfoDlg "$CENTEREDTXT"
}

function showUpdatesUpToDateDlg() {
	wrapTxtFn "$_UPTODATE"
	centerTxtFn "$WRAPPEDTXT"
	showMsgDlg "$CENTEREDTXT"
}

function showUpdateErrorDlg() {
	wrapTxtFn "$_ERRORCHECKUPDATE"
	centerTxtFn "$WRAPPEDTXT"
	showMsgDlg "$CENTEREDTXT"
}

function showUpdateAvailableDlg() {
	wrapTxtFn "$_ANUPDATE ($1) $_ISAVAILABLE"
	centerTxtFn "$WRAPPEDTXT"
	showConfirmDlg "$CENTEREDTXT"
}

function showInstallingUpdateDlg() {
        wrapTxtFn "$_INSTALLINGUPDATE"
        centerTxtFn "$WRAPPEDTXT"
        showInfoDlg "$CENTEREDTXT"
}

function showSystemUpdatedDlg() {
	wrapTxtFn "$_UPDATEDTO $1"
	centerTxtFn "$WRAPPEDTXT"
	showMsgDlg "$CENTEREDTXT"
}

function showUpdateErrorOccurredDlg() {
	wrapTxtFn "$_ERRORUPDATE"
	centerTxtFn "$WRAPPEDTXT"
	showMsgDlg "$CENTEREDTXT"
}
