#!/bin/bash
#
#Copyright 2012 CurlyMo <development@xbian.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>

function showPackageListDownloadDlg() {
        wrapTxtFn "$_DOWNLOAD_PL"
        centerTxtFn "$WRAPPEDTXT"
        showInfoDlg "$CENTEREDTXT"
}

function showPackageListErrorDlg() {
	wrapTxtFn "$_PL_ERROR"
	centerTxtFn "$WRAPPEDTXT"
	showMsgDlg "$CENTEREDTXT"
}

function showCheckingForUpdatesDlg() {
        wrapTxtFn "$_CHECKING_FOR_UD"
        centerTxtFn "$WRAPPEDTXT"
        showInfoDlg "$CENTEREDTXT"
}

function showUpToDateDlg() {
	wrapTxtFn "$_UP_TO_DATE"
	centerTxtFn "$WRAPPEDTXT"
	showMsgDlg "$CENTEREDTXT"
}

function showUpdateErrorDlg() {
	wrapTxtFn "$_ERROR_CHECK_UPDATE"
	centerTxtFn "$WRAPPEDTXT"
	showMsgDlg "$CENTEREDTXT"
}

function showUpdateAvailableDlg() {
	wrapTxtFn "$_AN_UPDATE ($TO_INSTALL) $_IS_AVAILABLE"
	centerTxtFn "$WRAPPEDTXT"
	showConfirmDlg "$CENTEREDTXT"
}

function showInstallingUpdateDlg() {
        wrapTxtFn "$_INSTALLING_UPDATE"
        centerTxtFn "$WRAPPEDTXT"
        showInfoDlg "$CENTEREDTXT"
}

function showSystemUpdatedDlg() {
	wrapTxtFn "$_UPDATED_TO $TO_INSTALL"
	centerTxtFn "$WRAPPEDTXT"
	showMsgDlg "$CENTEREDTXT"
}

function showErrorOccurredDlg() {
	wrapTxtFn "An error occurred while installing the update"
	centerTxtFn "$WRAPPEDTXT"
	showMsgDlg "$CENTEREDTXT"
}
