#!/bin/bash
#
#Copyright 2012 Hexagon <development@xbian.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>

#|------------------------------------|
#|          Global variables          |
#|------------------------------------|

# The arguments this module accepts
ARGUMENTS=(check update);

#|------------------------------------|
#|          Include files             |
#|------------------------------------|

source $BASEPATH/modules/updates/functions
source $BASEPATH/modules/updates/dialogs

#|------------------------------------|
#|           Main program             |
#|------------------------------------|

# Executes the GUI version of this module
function showGUIFn() {
	showPackageListDownloadDlg
	downloadPackageListFn
	if [ $? -eq 0 ]; then
		showPackageListErrorDlg
	else
		showCheckingForUpdatesDlg
		TOINSTALL=$(checkForUpdatesFn)
		if [ ! -z "$TOINSTALL" ]; then
			if [ "$TOINSTALL" = "0" ]; then
				# No new updates
				showUpdatesUpToDateDlg
			elif [ "$TOINSTALL" = "-1" ]; then
				# An error occurred
				showUpdateErrorDlg
			else
				# Update is available
				showUpdateAvailableDlg "$TOINSTALL"
				if [ $? -eq 0 ]; then
					showInstallingUpdateDlg
					installUpdateFn "$TOINSTALL"
					if [ $? -eq 1 ]; then
						# System updated
						showSystemUpdatedDlg "$TOINSTALL"
					else
						# An error occurred
						showUpdateErrorOccurredDlg
					fi
				fi
			fi
		fi
	fi

}

# Executes the command line version of this module
#  $1 Argument [Integer]
# Returns
#  *Check [String]
#  - Latest version
#  *Update [Integer]
#  - 1: Success
#  - 0: Failed
function showCMDFn() {
	case $1 in
		"check")
			downloadPackageListFn
			if [ $? -eq 0 ]; then
				echo 0;
			else
				TO_INSTALL=$(checkForUpdatesFn)
				if [ ! -z "$TO_INSTALL" ]; then
					if [ "$TO_INSTALL" = "0" ]; then
						echo "0"
					elif [ "$TO_INSTALL" = "-1" ]; then
						echo "-1"
					else
						echo "$TO_INSTALL"
					fi
				else
					echo "0"
				fi
			fi
		;;
		"update")
			installUpdateFn "$2"
			if [ $? -eq 1 ]; then
				echo 1;
			else
				echo 0;
			fi
		;;
	esac
}
