#!/bin/bash
#
#Copyright 2012 Hexagon <development@xbian.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>

_LOADINGINTERFACES="Interfaces loading, please wait ..."
_NOINTERFACES="No network interfaces available"
_SELECTINTERFACE="Select interface to configure"
_IPDHCP="DHCP"
_IPSTATIC="Static IP"
_SELECTHOW="Select how"; _OBTAINIP="should obtain it's IP address"

function showInterfacesSelectDlg() {
	# Prepare menu
        MENU=""
	IFACES="$1"
        I=1
        for IFACE in ${IFACES[@]}; do
                MENU+="$I%$IFACE%"
                I=$(($I+1))
        done

        # Show interface selector dialog
        showMenuDlg "$_SELECTINTERFACE" "$MENU"
}

function showIPModeConfigDlg() {

	# Radio states
	STATUSDHCP="off"
	STATUSSTATIC="off"

	# Pre-select current state
	if [ "$1" = "static" ]; then
		STATUSSTATIC="on"
	else
		STATUSDHCP="on"
	fi
	showRadioDlg "" "1%$_IPDHCP%$STATUSDHCP%2%$_IPSTATIC%$STATUSSTATIC" 3

}

function showInterfacesLoadingDlg() {
	wrapTxtFn "$_LOADINGINTERFACES"
	centerTxtFn "$WRAPPEDTXT"
	valignTxtFn "$CENTEREDTXT"
	showInfoDlg "$ALIGNEDTXT" $HEIGHT
}

function showNoInterfacesAvailableDlg() {
	wrapTxtFn "$_NOINTERFACES"
	centerTxtFn "$WRAPPEDTXT"
	valignTxtFn "$CENTEREDTXT"
	showMsgDlg "$ALIGNEDTXT" $HEIGHT
}
