#!/bin/bash
#
#Copyright 2012 Hexagon <development@xbian.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>

# ToDo:
# ----------------------------
# DEPRECATED , Should be built in in getStatus
#   - getInterfaceWlanCredentials "wlan0" # Return MODE ESSID KEY
# ----------------------------

# Set wlan credentials
# Arguments
#  $1 Interface name
#  $2 Protection (WPA|WEP|Open)
#  $3 ESSID
#  $4 KEY (Only needed for WPA and WEP)
# Return
#  1: Success
#  0: Failure
# Error codes
#  -10: Invalid wireless protection
setInterfaceWlanCredentials() {

	# Check that supplied interface is valid
        isValidInterfaceFn "$1"
	if [ $? -eq 1 ]; then

		# Create buffer for holding configuration
		WLANBUFFER=""
		case $2 in
			"WEP")
				WLANBUFFER+="\nwireless-essid $3\nwireless-key $4"
			;;
			"WPA")
				WLANBUFFER+="\nwpa-ssid \"$3\"\nwpa-psk \"$4\""
			;;
			"Open")
				WLANBUFFER+="\nwireless-mode managed\nwireless-essid $3"
			;;
			*)
				echo "-10"
				return 0
			;;
		esac

	        if [ $(cat /etc/network/interfaces | grep "^iface $1" | wc -l) -gt 0 ]; then

			# Interface already present, store it + any subsequent ifaces in an buffer
			IFACEBUFFER=$(cat /etc/network/interfaces | grep -A100 "^iface $1" | sed '1d');

			# Extract DHCP or Static
			MODE=$(cat /etc/network/interfaces | grep "iface $1" | cut -f 4 -d " ");

			# Remove what's now in the buffer from the file
			sed -i "/^iface $1/,+100d" /etc/network/interfaces

			# Extract subsequent ifaces to a separate buffer
			MORE=$(echo -e "$IFACEBUFFER" | sed -n '/\(allow-hotplug.*\|^iface.*\)/,$p')

			# Get a cleaned verson of current clause
			ME=$(echo -e "$IFACEBUFFER" | sed '/\(allow-hotplug.*\|^iface.*\)/,$d' | sed '/\(^wireless.*\|^wpa.*\)/d')

			# Re-add current interface withouth previous cruft
	                echo -e "iface $1 inet $MODE" >> /etc/network/interfaces
			echo -e "$WLANBUFFER" >> /etc/network/interfaces
			echo -e "$ME\n" >> /etc/network/interfaces

			# Re-add subsequent interfaces
			echo -e "$MORE" >> /etc/network/interfaces

			echo "1";
			return 1;
		else
			# Interface not present, add it to the end
			echo -e "iface $1 inet dhcp" >> /etc/network/interfaces
			echo -e "$WLANBUFFER\n" >> /etc/network/interfaces

			echo "1"
			return 1;
		fi


	else
		echo "-3"
		return 0;
	fi
}

# Sets an interface to use dhcp
# Arguments
#  $1 Interface name
setInterfaceDhcpFn() {
        isValidInterfaceFn "$1"
	if [ $? -eq 1 ]; then
	        if [ $(cat /etc/network/interfaces | grep "^iface $1" | wc -l) -gt 0 ]; then

			# Interface already present, store it + any subsequent ifaces in an buffer
			IFACEBUFFER=$(cat /etc/network/interfaces | grep -A100 "^iface $1" | sed '1d');

			# Remove what's now in the buffer from the file
			sed -i "/^iface $1/,+100d" /etc/network/interfaces

			# Extract subsequent ifaces to a separate buffer
			MORE=$(echo -e "$IFACEBUFFER" | sed -n '/\(allow-hotplug.*\|^iface.*\)/,$p')

			# Get a cleaned verson of current clause
			ME=$(echo -e "$IFACEBUFFER" | sed '/\(allow-hotplug.*\|^iface.*\)/,$d' | sed '/\(^address.*\|^netmask.*\|^gateway.*\)/d')

			# Re-add current interface withouth previous cruft
	                echo -e "iface $1 inet dhcp" >> /etc/network/interfaces
			echo -e "$ME\n" >> /etc/network/interfaces

			# Re-add subsequent interfaces
			echo -e "$MORE" >> /etc/network/interfaces

			return 1;
		else
			# Interface not present, add it to the end
			sudo echo -e "iface $1 inet dhcp\n" >> /etc/network/interfaces

			return 1;
		fi
	else
		echo "-3"
		return 0;
	fi
}

# Sets an interface to use static ip
# Arguments
#  $1 Interface name
#  $2 IP
#  $3 Netmask
#  $4 Gateway
#  $5 DNS1 (optional)
#  $6 DNS2 (optional)
# Returns
#  0: Failed
#  1: Succeede
# Error codes
#  -3: Invalid interface
#  -6: Invalid IP
#  -7: Invalid netmask
#  -8: Invalid Gateway
#  -9: Invalid DNS
setInterfaceStaticFn() {
        isValidInterfaceFn "$1"
	if [ $? -eq 1 ]; then

		# Configuration buffer
		BUFFERIFACES=""
		BUFFERRESOLV=""

		# Validate input & preparation of configuration buffers
		checkValidIpNumberFn "$2"
		if [ ! $? -eq 1 ]; then
			echo "-6"
			return 0;
		else
			BUFFERIFACES+="address $2"
		fi
		checkValidIpNetmaskFn "$3"
		if [ ! $? -eq 1 ]; then
			echo "-7"
			return 0;
		else
			BUFFERIFACES+="\nnetmask $3"
		fi
		checkValidIpNumberFn "$4"
		if [ ! $? -eq 1 ]; then
			echo "-8"
			return 0;
		else
			BUFFERIFACES+="\ngateway $4"
		fi
		if [ $# -gt 4 ] && [ ! -z "$5" ]; then
			checkValidIpNumberFn "$5"
			if [ ! $? -eq 1 ]; then
				echo "-9"
				return 0;
			else
				BUFFERRESOLV+="nameserver $5"
			fi
		fi
		if [ $# -gt 5 ] && [ ! -z "$6" ]; then
			checkValidIpNumberFn "$6"
			if [ ! $? -eq 1 ]; then
				echo "-9"
				return 0;
			else
				BUFFERRESOLV+="\nnameserver $6"
			fi
		fi

		# Process /etc/network/interfaces
	        if [ $(cat /etc/network/interfaces | grep "^iface $1" | wc -l) -gt 0 ]; then

			# Interface already present, store it + any subsequent ifaces in an buffer
			IFACETMP=$(cat /etc/network/interfaces | grep -A100 "^iface $1" | sed '1d');

			# Remove what's now in the buffer from the file
			sed -i "/^iface $1/,+100d" /etc/network/interfaces

			# Extract subsequent ifaces to a separate buffer
			MORE=$(echo -e "$IFACETMP" | sed -n '/\(allow-hotplug.*\|^iface.*\)/,$p')
			ME=$(echo -e "$IFACETMP" | sed '/\(allow-hotplug.*\|^iface.*\)/,$d' | sed '/\(^address.*\|^netmask.*\|^gateway.*\)/d')

			# Re-add current interface withouth previous cruft
	                echo -e "iface $1 inet static" >> /etc/network/interfaces
			echo -e "$ME" >> /etc/network/interfaces
			echo -e "$BUFFERIFACES\n" >> /etc/network/interfaces

			# Re-add subsequent interfaces
			echo -e "$MORE" >> /etc/network/interfaces

		else
			# Interface not present, add it to the end
			sudo echo -e "iface $1 inet static" >> /etc/network/interfaces
			echo -e "$BUFFERIFACES\n" >> /etc/network/interfaces

		fi

		# Process /etc/resolv.conf
		sed -i "/nameserver/d" /etc/resolv.conf
		echo -e "$BUFFERRESOLV" >> /etc/resolv.conf

		echo "1"
		return 1;
	else
		echo "-3"
		return 0;
	fi
}

# List all available network interfaces
# Echoes @return
#  @1: Available interfaces
#  @2: Error code
# Returns
#  1: Success
#  0: Error
function listNetworkInterfacesFn() {
	# List all interfaces
	IFACES=$(ip addr | grep state | grep -v lo: | cut -f 2 -d":" | sed 's/ //g')
	if [ ! -z "$IFACES" ]; then
		echo "$IFACES"
		return 1
	else
		echo "-3"
		return 0
	fi
}

# Check if a given string is a valid interface name
# Parameters
#  $1: Interface name
# Returns
#  1: Valid
#  0: Invalid
function isValidInterfaceFn() {
	INTERFACE=$(listNetworkInterfacesFn | grep "$1")
	if [ ! -z "$INTERFACE" ]; then
		return 1;
	else
		return 0;
	fi
}

# Reads various netowrk configuration options from related files
# Arguments
#   $1 Interface
# Return
#   1: Success
#   0: Failure
# Echoes
#   @1: Textual table
#       -----------------------
#       MODE dhcp|static|manual
#       IP X.X.X.X
#       NETMASK X.X.X:X
#       GATEWAY X.X.X.X
#       NAMESERVER1 X.X.X.X
#       NAMESERVER2 X.X.X.X
#   @0: Error code
# Error codes
#   -4: Invalid interface
function readNetworkConfigurationFn() {
        isValidInterfaceFn "$1"
	if [ $? -eq 1 ]; then
		# Read network configuration from /etc/network/interfaces
		TFILEIFACES=$(cat /etc/network/interfaces)

		# Place everything after matching iface in a variable
		CONTENT=$(echo -e "$TFILEIFACES" | grep -A20 "^iface $1 inet" | sed '1d');

		# Delete (possible) subsequent ifaces from variable
		CONTENT=$(echo -e "$CONTENT" | sed '/iface/,$d');

		# Extract DHCP or Static
		MODE=$(echo -e "$TFILEIFACES" | grep "iface $1" | cut -f 4 -d " ");

		# Extract manual ip configuration
		CIP=$(echo -e "$CONTENT" | grep address | cut -f 2 -d " ");
		CSM=$(echo -e "$CONTENT" | grep netmask | cut -f 2 -d " ");
		CGW=$(echo -e "$CONTENT" | grep gateway | cut -f 2 -d " ");

		# Extract wlan configuration
		PROTECTION=""
		MODEOPEN=$(echo -e "$CONTENT" | grep ^wireless-mode)
		MODEWPA=$(echo -e "$CONTENT" | grep ^wpa-)
		MODEWEP=$(echo -e "$CONTENT" | grep ^wireless-essid)
		if [ ! -z "$MODEOPEN" ]; then
			PROTECTION="Open"
		elif [ ! -z "$MODEWPA" ]; then
			PROTECTION="WPA"
		elif [ ! -z "$MODEWEP" ]; then
			PROTECTION="WEP"
		fi

		# Extract wlan credentials
		SSID=""
		KEY=""
		if [ ! -z "$PROTECTION" ]; then
			if [ "$PROTECTION" = "WEP" ]; then
				SSID=$(echo -e "$CONTENT" | grep wireless-essid | cut -f 2 -d" ")
				KEY=$(echo -e "$CONTENT" | grep wireless-key | cut -f 2 -d" ")
			elif [ "$PROTECTION" = "WPA" ]; then
				SSID=$(echo -e "$CONTENT" | grep wpa-ssid | cut -f 2 -d" " | sed 's/\"//g')
				KEY=$(echo -e "$CONTENT" | grep wpa-psk | cut -f 2 -d" " | sed "s/\"//g")				
			elif [ "$PROTECTION" = "Open" ]; then
				SSID=$(echo -e "$CONTENT" | grep wireless-essid | cut -f 2 -d" ")
			fi
		fi

	        # Read nameservers from /etc/resolv.conf
	        NS1="";
	        NS2="";
	        if [ $(cat /etc/resolv.conf | grep nameserver | wc -l) -gt 0 ]; then
	           NS=($(cat /etc/resolv.conf | grep nameserver | sed 's/nameserver //g' ))
	           if [ ${#NS[@]} -gt 0 ]; then
	              NS1=$(echo -e "${NS[0]}");
	           fi
	           if [ ${#NS[@]} -gt 1 ]; then
	              NS2=$(echo -e "${NS[1]}");
	           fi
	        fi
		echo "MODE $MODE"
		echo "IP $CIP"
		echo "NETMASK $CSM"
		echo "GATEWAY $CGW"
		echo "NAMESERVER1 $NS1"
		echo "NAMESERVER2 $NS2"
		if [ ! -z "$PROTECTION" ]; then
			echo "PROTECTION $PROTECTION"
			echo "SSID $SSID"
			echo "KEY $KEY"
		fi
		return 1;
	else
		echo "-1"
		return 0;
	fi
}

# Validate a given ip address
# Arguments
#  $1 Ip address
# Return
#  1: Valid
#  0: Invalid
function checkValidIpNumberFn() {
        if case $1 in
                *[!.0-9]* | *.*.*.*.* | *..* | [!0-9]* | *[!0-9] ) false ;;
                *25[6-9]* | *2[6-9][0-9]* | *[3-9][0-9][0-9]* | *[0-9][0-9][0-9][0-9]* ) false ;;
                [!1-9].*.*.* | *.*.*.[!1-9] ) false ;;
                *.*.*.* ) true ;;
                *) false ;;
        esac; then
		# Ip were valid
		return 1;
	else
		# Ip were invalid
		return 0;
        fi
}

# Validate a given netmask
# Arguments
#  $1 Netmask
# Return
#  1: Valid
#  0: Invalid
function checkValidIpNetmaskFn() {
        if case $1 in
                255.0.0.0 | 255.255.0.0 | 255.255.255.0 | 255.255.255.255 ) true ;;
                *) false ;;
        esac; then
		return 1
	else
		return 0
        fi
}
