#!/bin/bash
#
#Copyright 2012 CurlyMo <development@xbian.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>

function rootPasswordSetFn() {
	if [ -z $(cat /etc/shadow | grep root | cut -f 2 -d:) ]; then
		return 0;
	else
		return 1;
	fi
}

function enableSSHRootLoginFn() {
	sed -i 's/PermitRootLogin no/PermitRootLogin yes/g' /etc/ssh/sshd_config
	/etc/init.d/ssh restart >/dev/null
	isSSHRootLoginEnabledFn
	return $?;
}

function disableSSHRootLoginFn() {
	sed -i 's/PermitRootLogin yes/PermitRootLogin no/g' /etc/ssh/sshd_config
	/etc/init.d/ssh restart >/dev/null
	isSSHRootLoginEnabledFn
	return $?;
}

function isSSHRootLoginEnabledFn() {
	if [ $(cat /etc/ssh/sshd_config | grep "PermitRootLogin yes" | wc -l) -eq 0 ]; then
		return 0;
	else
		return 1;
	fi
}