#!/bin/bash
#
#Copyright 2012 CurlyMo <development@xbian.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>

ARGUMENTS=(status rootpass enable disable);
source $BASEPATH/scripts/sshroot/functions
source $BASEPATH/scripts/sshroot/dialogs

function showGUIFn() {
	rootPasswordSetFn
	if [ $? -eq 0 ]; then
		showEmptyRootPasswordDlg 
		return 1;
	fi
	
	enableDisableSSHRootLoginDlg
	if [[ $? -eq 0 ]]; then
		enableSSHRootLoginFn
		if [[ $? -eq 0 ]]; then
			showErrorDlg;
		else
			showSSHRootEnabledDlg
		fi
	else
		disableSSHRootLoginFn
		if [[ $? -eq 1 ]]; then
			showErrorDlg;
		else
			showSSHRootDisabledDlg
		fi
	fi
}

function showCMDFn() {
	case $1 in
		"status")
			isSSHRootLoginEnabledFn;
			return $?;
		;;
		"rootpass")
			rootPasswordSetFn;
			return $?;
		;;
		"enable")
			enableSSHRootLoginFn;
			return $?;
		;;
		"disable")
			disableSSHRootLoginFn;
			return $?;
		;;
	esac
	return 0;
}